import mongoose from 'mongoose';
const HotelSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    type:{
        type:String,
        required:true,
    },
    city:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    },
    distance:{
        type:String,
    },
    photos:{
        type:[String],
        required:true,
    },
    title:{
        type:String,
        required:true,
    },
    desc:{
        type:String,
        required:true,
    },
    rating:{
        type:Number,
        min:0,
        max:10,
    },
    rooms:{
        type:[String],
    },
    cheapestPrice:{
        type:Number,
        required:true,
    },
   popularHotel:{
        type:Boolean,
        default:false,
    },
    comments:{
        type:Number,
        default:0,
    }
})
export default mongoose.model("Hotel",HotelSchema)
